[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
lib-core = { path = "../../libs/lib-core" }
lib-image = { path = "../../libs/lib-image" }
lib-ascii = { path = "../../libs/lib-ascii" }
ffmpeg-next = "8.0.0"
crossterm = "0.29.0"
scopeguard = "1.2.0"
termsize = "0.1.9"
