[workspace]
resolver = "3"
members = [
  "crates/libs/glyphforge-core",
  "crates/libs/glyphforge-ascii",
  "crates/libs/glyphforge-image",
  "crates/services/glyphforge-cli",
]

[workspace.dependencies]
pretty_assertions = "1.4.1"
