[workspace]
resolver = "3"
members = [
  "crates/libs/lib-core",
  "crates/libs/lib-ascii",
  "crates/libs/lib-image",
  "crates/services/cli",
]

[workspace.dependencies]
pretty_assertions = "1.4.1"
